server: 
  port: 8181
  servlet:
    context-path: /sample-api
spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
logging: 
  level: 
    root: WARN
    org: 
      springframework: 
        web: DEBUG
      hibernate: ERROR      
log4j: 
  rootLogger: DEBUG, DebugAppender        